sudo: required
services:
  -docker :

before_install:
  - docker build -t nirajbankar/docker-react -f Dockerfile.dev .

script:
  - docker run nirajbankar/docker-react npm run ci_test -- --coverage
language: minimal

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucker_name: "elasticbeanstalk-us-east-1-427742824532"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

  
  
   