sudo: required
services:
  -docker :

before_install:
  - docker build -t nirajbankar/docker-react -f Dockerfile.dev .

script:
  - docker run nirajbankar/docker-react npm run ci_test -- --coverage
language: minimal